import { createSlice } from '@reduxjs/toolkit'

const counterSlice = createSlice({ // Create a slice for managing the counter state
    name: 'counter',   // The name of the slice, which is used to identify the slice in the Redux store (chef's)
    initialState: {   // The initial state of the counter for holding data
        count: 0
    },
    reducers: {      // The reducers are functions that handle actions and update the state accordingly (action handlers - recipes)
        increment: (state) => {  //state - The current state of the counter slice, which is passed as an argument to the reducer function
            state.count += 1
        },
        decrement: (state) => {
            state.count -= 1
        }
    }
})

console.log("slice -> ", counterSlice)  // Log the counterSlice object to the console for debugging purposes

export const { increment, decrement } = counterSlice.actions  // Export the action creators generated by createSlice for the increment and decrement actions

export default counterSlice.reducer  // Export the reducer function generated by createSlice for the counter slice

